---
title: "homework_5"
author: "Matthew Lawlor"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
```

## Read and tidy data

```{r}
homicide_df = read.csv("./data/homicide_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = paste(city, state, sep = ", ")
  )
```

Homicides per city

```{r}
total_homicides =
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    n_homicides = n(),
  )
```

Number of unsolved homicides per city

```{r}
unsolved_homicides =
  homicide_df %>%
  filter(disposition == "Closed without arrest" | disposition == "Open/No arrest") %>% 
  group_by(city_state) %>% 
  summarize(
    n_open_homicides = n()
  )
```

DF of total and unsolved homicides

```{r}
open_total_homicides =
    full_join(unsolved_homicides, total_homicides)

open_total_homicides[is.na(open_total_homicides)] <- 0
```

Proportion of homicides that are unsolved in Baltimore, MD

```{r}
baltimore_homicides = 
open_total_homicides %>% 
  filter(city_state == "Baltimore, MD")

output = prop.test(x = baltimore_homicides$n_open_homicides, n = baltimore_homicides$n_homicides)

output %>% broom::tidy()
```

p = 0.646 (95% CI 0.628-0.663)

prop.test(open_total_homicides$n_open_homicides, open_total_homicides$n_homicides)

Proportion of homicides that are unsolved across cities

```{r, error = TRUE}
##need to figure out how to turn list into vector
output = map2_df(.x = open_total_homicides$n_open_homicides, .y = open_total_homicides$n_homicides, ~prop.test(x = .x, n = .y), .id = "city_state")

```


